---
title: "Estimate parturition in caribou using the TuktuTools Package"
author: "Ophélie Couriot"
date: "12/14/2022"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette_parturition}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, echo = FALSE)
```

The TuktuTools Package has been developed to analyse caribou movement data. 
This package contains several functions allowing to:
- Visualize movement data
- Clean and process movement data
- Get the movement rate between successive locations for each individuals
- Get the euclidean distance between each pairs of individuals from a dataset
- Get the utilisation distribution of an individual or all individuals during a given period
- Discriminate between parturient and non parturient individuals and get the parturition timing and location
- ...

The *`parturition.model`* is a function allowing to estimate calving (i.e. parturition) status and calving dates in  caribou (*Rangifer tarandus*), using an individual based method developped by DeMars et al. (2013). This method infers calving status and neonate survival from female caribou movement patterns. In particular, DeMars et al. predicted that calving events could be identified by a sudden and marked change – or break point – in female mean step length (i.e. the distance between two successive relocations). The method assumes that, for calving, a female would depresse her movements and that movement rates would remain low as long as the calf was alive, since neonates are not able to move as adults, thus acting as a spatial “anchor”. Conversely, if the calf was lost during the neonatal period, a second break point would occur in the female movement pattern, since the female would recover her pre-calving movements abruptly, due to calf loss. Non calving female would have a constant movement rate throughout the entire calving period.

While this method has proven good reliability, it requires an homogeneous time series (i.e. homogeneous time interval between successive relocations). To dispense with data homogenization, we adapted this method by performing analyses on speed (i.e. the distance travelled between two successive relocations on the time between these two relocations) instead of step length.

This document describes the data and the steps to clean data, estimate calving date and location. 
